### ISSUE TITLE
How to add child React elements?

### ISSUE THREAD

**Issue by jpap** [ljbc1994/babel-plugin-react-pug#3]
How can we include a react element as a child?

The trivial example given below fails to compile. 

```
const Div = (props) => {
  return pug`
    div
      ${ props.children }
  `;
};
```

Similar constructs come up often with `props.children` and other child elements that come from a Javascript variable.

**Comment by ljbc1994** [comment]
Hey, thanks for raising this issue!

You can include react element children by inlining the `${ props.children }` so:

```js
const Div = (props) => {
  return pug`
    div ${ props.children }
  `;
};
```

**Comment by jpap** [comment]
I also worked that out and found it awkward, because I end up having these extra `div`s in the DOM hierarchy as children of an `a`, for example, that impacted my existing CSS selectors.

I've since returned to [babel-plugin-transform-pug-to-react](https://github.com/e-jigsaw/babel-plugin-transform-pug-to-react) where I can do
```
const Blah = (props) => {
   return pug`
      .blah
         = props.children
   `;
}
```
but the thing I dislike about their approach is that without the `${ ... }` decorators, ESLint doesn't recognize the contents and therefore unnecessarily flags many variables as being unused.  I would much rather be using this project instead!  (My sincere thanks for the work you've dedicated to it.)

I recall also running into another scenario that just refused to compile, where the `div` approach failed.  Let me try and go back to create a well-defined example and return with something concrete.

Is it much work to support child elements without the `div`?

**Comment by ljbc1994** [comment]
Ah I see! I've pinpointed where the issue arises from and have a fix in place, wasn't too much trouble. So you should be able to have nested children without inlining the js in a pug element.

**Comment by ljbc1994** [comment]
Should be fixed with release 0.4.7. Please give it a go 😄

**Comment by jpap** [comment]
Thanks for the quick update!

Unfortunately I get errors now,
```
Uncaught Error: Expected onClick listener to be a function, instead got type object
```
where this happens a lot for properties, for example one expecting a `PropTypes.bool`, even when I replace the property value with just `${ true }`.

Going back to the previous version, and the above discussion where I promised to get back to you, the other issue I had when I tried using inline `div`s previously was that passing React components/objects via attributes failed when they were inlined.  I'm not sure if that's related, or a separate bug?

For example, the following didn't work on the old version:
```
const Button = (props) => {
  const onClick = (e) => {
    if (props.onClick) {
      props.onClick();
    }
  };

  return pug`
    button(onClick=${ onClick })
      div ${ props.label }
  `;
};

Button.propTypes = {
  label: PropTypes.oneOfType([PropTypes.string, PropTypes.object]).isRequired,
  onClick: PropTypes.func,
};
```

The error message for the above was something like:
```
react-dom.js:17985 Uncaught Error: Objects are not valid as a React child (found: /~16~/). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Button`.
```
Of course in this case I could use `props.children`, but passing React elements via attributes should be legal.  (They work with [babel-plugin-transform-pug-to-react](https://github.com/e-jigsaw/babel-plugin-transform-pug-to-react).)

Appreciate your help on this! :D

**Comment by ljbc1994** [comment]
Thanks for providing info! Yeah I jumped the gun a lil' bit, I've now *hopefully* corrected the issue that has resulted from the original fix with the latest release.

With regard to the second issue encountered, if this persists could you raise another issue for this?

No problem 👍

**Comment by jpap** [comment]
That was quick -- thank you! :D

Version 0.4.9 works really well; the issue with passing a React component via an attribute works now too... so they may have been related after all?!
