### ISSUE TITLE
Differences from the official babel-plugin-transform-react-pug

### ISSUE THREAD

**Issue by ForbesLindesay** [ljbc1994/babel-plugin-react-pug#5]
Hi, I maintain pug, and released https://github.com/pugjs/babel-plugin-transform-react-pug quite a while ago.  Unfortunately, I haven't had time to actually document the usage properly, but essentially you just add the `babel-plugin-transform-react-pug` and `babel-plugin-transform-react-jsx` to your babelrc file, then it will behave pretty similarly to this module.

Would you mind having a look and seeing if you could contribute back to the official plugin, rather than starting a separate project?

**Comment by ljbc1994** [comment]
Hi Forbes, I know of your work 👍, thanks for all you've done with Pug and `redux-optimist`!  

Before I started on the plugin I did have a look at yours and `babel-plugin-transform-pug-to-react`, the reasons why I did my own was to make use of template literals + interpolations (made it work with code editors seamlessly and eslint) and include aspects of Pug that I felt most applied to react components. 

In the meantime, I can put a note at the top of the README to say that it's not the official plugin and direct users to yours? Or I can change the name of the plugin (as it should really follow the `babel-plugin-transform` convention)?

I'm not sure if yours does it, but does your plugin convert directly to function calls or JSX?

**Comment by ForbesLindesay** [comment]
Hi, a note at the top of the README would be great.  When I wrote the first version of react-jade, it converted directly to function calls, but React changed the API, so I decided it was better to convert to JSX.  This also lets me take advantage of all the JSX only babel optimisations, such as automatically extracting constant elements.

Mine doesn't currently use interpolations, although support could be added fairly easily I think, since it is already tagged template literals.

**Comment by ljbc1994** [comment]
Cool, will chuck a note on the README and release it when I'm free today.

Aha that makes sense, this plugin doesn't leverage the benefits of Babel's JSX support at all or support pug iterations and scope so I'd love to dive into the code for your plugin. So, when time permits, I'll have a look and contribute to `babel-plugin-transform-react-pug` 👍
