### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by jpap** [ljbc1994/babel-plugin-react-pug#6]
I'm migrating to TypeScript and I'd love to continue using this fantastic plugin.

I currently get errors when doing so,
```
error TS2304: Cannot find name 'pug'.
```
and I'm not really sure how to proceed with creating typings or otherwise.

Any help appreciated.

**Comment by jpap** [comment]
I was able to solve this by creating the file: `node_modules/@types/babel-plugin-react-pug/index.d.ts` with contents:
```
declare var pug: any;
```

I'm not sure if there's any merit to providing a type that's more specific than `any`.

I will now look at contributing this to the `@types` project.  It appears that including a type definition in this project *will not help*, as there is no explicit `import` of the `react-pug` babel plugin in each source file: it must be a "global" type definition.

**Comment by jpap** [comment]
Type [contribution can be found here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/19645).

Should we add a comment to the README for this?

**Comment by ljbc1994** [comment]
Ah great, thanks, really appreciate this!

I'll add this to the README!
